version: '3.7'
services:
  nodejs:
    container_name: services_api
    build:
      context: .
      dockerfile: nodejs.dockerfile
    restart: on-failure
    volumes:
      - .:/api
    environment: 
      - "NODE_ENV=development"
    # ports:
    #   - 8002:8002
    external_links:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "rabbitmq:5672", "--", "npm", "run", "dev"]
  nginx:
    container_name: services_nginx_reverse_proxy
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 90:90
    depends_on:
      - services_api
    restart: on-failure
  rabbitmq:
    container_name: services_rabbitmq
    build:
      context: .
      dockerfile: rabbitmq.dockerfile
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=transybao"
      - "RABBITMQ_DEFAULT_PASS=Transybao93!"
      - "RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.8"
  
networks:
  default:
    external: 
      name: bao_network
